### ISSUE TITLE
Errors with the last version & Unity 5 32bit

### ISSUE THREAD

**Issue by cduquesne** [patricksebastien/libpd4unity#17]
Hi ! 

With the last version of libpd4unity I encounter the following errors : 
- First, unsafe context is by default not accepted. The user needs to add a file in the Assets folder named "**gmcs.rsp**" with a single line of text "**-unsafe**". (Took a while to find out this one, so maybe the file could be added to the repo ?)
- Second, I have two compilation errors that I can't figure out : 
  `Assets/LibPdFilterRead.cs(52,31): error CS1502: The best overloaded method match for "LibPDBinding.LibPD.Process(int, double*, double*)" has some invalid arguments`
  and 
  `Assets/LibPdFilterRead.cs(52,31): error CS1503: Argument "#2" cannot convert "System.IntPtr" expression to type "double*"`

I don't have these errors with the versions before the last commits (i downloaded a version the 3rd October and it has no errors)

Does someone have an idea about these ? (I'm not familiar with pointers so I can't really know what's going on)
Thanks !

**Comment by batchku** [comment]
I'm trying to get libpd4unity working with Unity 5.4.1f1 on OS X.
I'm running into the first issue that cduquense mentions, regarding "unsafe":
Here is my error:

Assets/LibPD/LibPDNativeMethods.cs(313,42): error CS0227: Unsafe code requires the `unsafe' command line option to be specified

I've tried creating  a file in the Assets folder named "gmcs.rsp" with a single line of text "-unsafe".  This did not solve my problem.

Has anyone gotten libpd4unity working with Unity 5?

ali

**Comment by cduquesne** [comment]
I rolled back to an older version, and had the thing work, but with many random crashes that looked like memory corruption... Not usable at the moment it seems.
